# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ngCMatrix_to_array_test <- function(obj) {
    .Call('_spamming_ngCMatrix_to_array_test', PACKAGE = 'spamming', obj)
}

hamming_ngCMatrix_x_only <- function(obj) {
    .Call('_spamming_hamming_ngCMatrix_x_only', PACKAGE = 'spamming', obj)
}

hamming_ngCMatrix_x_and_y <- function(objx, objy) {
    .Call('_spamming_hamming_ngCMatrix_x_and_y', PACKAGE = 'spamming', objx, objy)
}

hamming_find_mode <- function(obj) {
    .Call('_spamming_hamming_find_mode', PACKAGE = 'spamming', obj)
}

test_conversion <- function(obj) {
    .Call('_spamming_test_conversion', PACKAGE = 'spamming', obj)
}

