# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hamming_ngCMatrix_x_only <- function(obj) {
    .Call('_spamming_hamming_ngCMatrix_x_only', PACKAGE = 'spamming', obj)
}

hamming_ngCMatrix_x_and_y <- function(objx, objy) {
    .Call('_spamming_hamming_ngCMatrix_x_and_y', PACKAGE = 'spamming', objx, objy)
}

